#!/bin/bash

if [ "$1" = "DEBUG" ] ; then
	set -x
	shift
fi

if [ $(id -u) -ne 0 ] ; then
       echo "WARNING:" \
       	    "This script requires ROOT privileges"
fi       


IPSEC=$(which ipsec)
test -x ${IPSEC} || echo "'ipsec' not found in PATH" 

CLASSID=0x000a000a
IPMARK=100

print_help()
{
	echo -n "Usage: "
	echo "$0   on | off | status | restart" 
}

switch_gateway()
{
	echo $1 >> /sys/fs/cgroup/net_cls/service/kodi/net_cls.classid
	cat /sys/fs/cgroup/net_cls/service/kodi/net_cls.classid
}

restore_gateway()
{
	echo 0x0 >> /sys/fs/cgroup/net_cls/service/kodi/net_cls.classid
	cat /sys/fs/cgroup/net_cls/service/kodi/net_cls.classid
}


case $1 in

	'on')
		echo -n "net_cls.classid: "
		switch_gateway $CLASSID
		echo ">> CONNECTION <<"
		${IPSEC} status 
		ping -m $IPMARK -c 3 www.google.com ;;

	'off')
		echo -n "net_cls.classid: "
		restore_gateway ;;

	'ping')
		ping -m $IPMARK -c 3 www.google.com ;;

	'status')
		echo -n "net_cls.classid: "
		cat /sys/fs/cgroup/net_cls/service/kodi/net_cls.classid
		echo ">> CONNECTION <<"
		${IPSEC} status
		ping -m $IPMARK -c 3 www.google.com ;;

	'restart')
		${IPSEC} restart ;;

	'help')
		print_help ;;

	*)
		print_help 
		echo "'$1' is not a valid option" ;;

esac
