#!/bin/bash

if [ "$1" = "DEBUG" ] ; then
	set -x
	shift
fi

if [ $(id -u) -ne 0 ] ; then
       echo "WARNING:" \
       	    "This script requires ROOT privileges"
fi       


IPT=$(which iptables)
IPSEC=$(which ipsec)
CHAIN=mwe-mangle-iptv
MARK_DE=100

test -x ${IPT} || echo "'iptables' not found in PATH" 
test -x ${IPSEC} || echo "'ipsec' not found in PATH" 

print_help()
{
	echo -n "Usage: "
	echo "$0   on | off | status | restart" 
}


switch_gateway()
{
	# flush 'iptv' chain
	# ${IPT} -t mangle -F ${CHAIN}
	# switch default gateway to X vpn connection
	${IPT} -t mangle -I ${CHAIN} 1 ! -d 192.168.14.0/24 -j MARK --set-mark $1
        # always maintain access to tvheadend server in Germany	
	# ${IPT} -t mangle -A ${CHAIN} -d 192.168.210.1 -j MARK --set-mark $MARK_DE
	# continue processing rest of chain
	# ${IPT} -t mangle -A ${CHAIN} -j RETURN
}

restore_gateway()
{
	${IPT} -t mangle -D ${CHAIN} 1
	# flush 'iptv' chain
	# ${IPT} -t mangle -F ${CHAIN}
        # always maintain access to tvheadend server in Germany	
	# ${IPT} -t mangle -A ${CHAIN} -d 192.168.210.1 -j MARK --set-mark $MARK_DE
	# continue processing rest of chain
	# ${IPT} -t mangle -A ${CHAIN} -j RETURN
}


case $1 in

	'on')
		switch_gateway $MARK_DE
		echo ">> CONNECTION <<"
		${IPSEC} status 
		echo ">> IPTABLES <<"
		${IPT} -t mangle -vL $CHAIN 
		ping -c 5 www.google.com ;;

	'off')
		restore_gateway 
		echo ">> IPTABLES <<"
		${IPT} -t mangle -vL $CHAIN ;;

	'ping')
		ping -c 5 www.google.com ;;

	'status')
		echo ">> CONNECTION <<"
		${IPSEC} status
		echo ">> IPTABLES <<"
		${IPT} -t mangle -vL $CHAIN ;;

	'restart')
		${IPSEC} restart ;;

	'help')
		print_help ;;

	*)
		print_help 
		echo "'$1' is not a valid option" ;;

esac
