#!/bin/bash

if [ "$1" = "DEBUG" ] ; then
	set -x
	shift
fi

if [ $(id -u) -ne 0 ] ; then
       echo "WARNING:" \
       	    "This script requires ROOT privileges"
fi       


IPSEC=$(which ipsec)
test -x ${IPSEC} || echo "'ipsec' not found in PATH" 

CLASSID=0x000a000a
IPMARK=100

print_help()
{
	echo -n "Usage: "
	echo "$0 start | stop | status | restart | help" 
}

switch_gateway()
{
	echo $1 >> /sys/fs/cgroup/net_cls/service/kodi/net_cls.classid
	cat /sys/fs/cgroup/net_cls/service/kodi/net_cls.classid
}

restore_gateway()
{
	echo 0x0 >> /sys/fs/cgroup/net_cls/service/kodi/net_cls.classid
	cat /sys/fs/cgroup/net_cls/service/kodi/net_cls.classid
}

status()
{
	echo ">> KODI net_clsid <<"
	cat /sys/fs/cgroup/net_cls/service/kodi/net_cls.classid
	echo
	echo ">> IPSEC Status <<"
	${IPSEC} status 
	echo
	echo ">> Ping Status <<" 
	echo ">trying ping via tunnel"
	ping -m $IPMARK -c 3 www.google.com
	echo
	echo ">trying ping w/out tunnel"
	ping -c 3 www.google.com

}


case $1 in

	'start')
		switch_gateway $CLASSID ;;

	'stop')
		restore_gateway ;;

	'status')
		status ;;

	'restart')
		${IPSEC} restart ;;

	'help')
		print_help ;;

	*)
		print_help 
		echo "'$1' is not a valid option" ;;

esac
