#!/bin/bash

if [ "$1" = "DEBUG" ] ; then
	set -x
	shift
fi

if [ $(id -u) -ne 0 ] ; then
       echo "WARNING:" \
       	    "This script requires ROOT privileges"
fi       


IPT=$(which iptables)
IPSEC=$(which ipsec)
CHAIN=iptv
MARK_DE=100
MARK_UK=101
InstId_DE=
InstId_UK=i-0ca62d6e97b0b70e4

test -x ${IPT} || echo "'iptables' not found in PATH" 
test -x ${IPSEC} || echo "'ipsec' not found in PATH" 

print_help()
{
	echo "usage:"
	echo "$0 on | on-uk | off | up-uk | down-uk | status | restart | update-ip" 
}


switch_gateway()
{
	# flush 'iptv' chain
	${IPT} -t mangle -F ${CHAIN}
	# switch default gateway to X vpn connection
	${IPT} -t mangle -A ${CHAIN} ! -d 192.168.14.0/24 -j MARK --set-mark $1
        # always maintain access to tvheadend server in Germany	
	${IPT} -t mangle -A ${CHAIN} -d 192.168.210.1 -j MARK --set-mark $MARK_DE
	# continue processing rest of chain
	${IPT} -t mangle -A ${CHAIN} -j RETURN
}

restore_gateway()
{
	# flush 'iptv' chain
	${IPT} -t mangle -F ${CHAIN}
        # always maintain access to tvheadend server in Germany	
	${IPT} -t mangle -A ${CHAIN} -d 192.168.210.1 -j MARK --set-mark $MARK_DE
	# continue processing rest of chain
	${IPT} -t mangle -A ${CHAIN} -j RETURN
}

start_vpn()
{
	aws ec2 start-instances --region eu-west-2 --instance-ids ${InstId_UK} 
	sleep 30
	update_ip
	ipsec reload
	ipsec up iptv_aws_uk
	ipsec status iptv_aws_uk
	switch_gateway $MARK_UK
}

stop_vpn()
{
	ipsec down iptv_aws_uk
	restore_gateway
	update_ip CLEAR
	aws ec2 stop-instances --region eu-west-2 --instance-ids ${InstId_UK} 
}

update_ip()
{
	if [ "$1" == "CLEAR" ] ; then
	       sed -i.old "/iptv_uk/ d" /etc/hosts
	       rm /etc/ipsec.d/iptv_aws_uk.dns
	       ipsec reload
	else
		IP_UK=$(aws ec2 describe-instances --region eu-west-2 --instance-ids ${InstId_UK} | \
			sed -n '/"PublicIpAddress"/ {s/[^0-9.]*//gp;q}')
		if [ -n "$IP_UK" ] ; then
		       echo "Public IP address: $IP_UK"
		       sed -i.old "/iptv_uk/ d" /etc/hosts
		       echo "$IP_UK	iptv_uk" >> /etc/hosts
		       echo "right=$IP_UK" > /etc/ipsec.d/iptv_aws_uk.dns
		fi
		PRIV_UK=$(aws ec2 describe-instances --region eu-west-2 --instance-ids ${InstId_UK} | \
			sed -n '/"PrivateIpAddress"/ {s/[^0-9.]*//gp;q}')
		if [ -n "$PRIV_UK" ] ; then
		       echo "Private IP address: $PRIV_UK"
		       echo "$PRIV_UK	iptv_uk_p" >> /etc/hosts
		fi
	fi	
}


case $1 in

	'on')
		switch_gateway $MARK_DE ;;

	'on-uk')
		switch_gateway $MARK_UK ;;

	'up-uk')
		start_vpn ;;

	'down-uk')
		stop_vpn ;;

	'off')
		restore_gateway ;;

	'status')
		echo ">> CONNECTION <<"
		${IPSEC} status
		echo ">> IPTABLES <<"
		${IPT} -t mangle -vL $CHAIN ;;

	'restart')
		${IPSEC} restart ;;

	'update-ip')
		shift
		update_ip $* ;;

	'help')
		print_help ;;

	*)
		echo "${0}: '$1' is not a valid option"
		print_help ;;

esac
